import pyautogui
import pyperclip

# 1. 키보드 입력 (문자)
# pyautogui.write('startcoding', interval=0.25)
# pyautogui.write('스타트코딩')  # 한글 안됨

# 2. 키보드 입력 (키)
# pyautogui.press('enter') 아래로 엔터
# pyautogui.press('up') 위로

# 3. 키보드 입력 (여러개 동시에)
# pyautogui.hotkey('ctrl', 'c') # mac = command
# 복사하는구간 복사하는구간 복사하는구간

# 4. 한글 입력 방법
# pyperclip.copy('한글입력하는구간')
# pyautogui.hotkey('ctrl', 'v')
# 한글입력하는구간 한글입력하는구간 한글입력하는구간

